// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedlatandlongattributetoemployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlatandlongattributetoemployees));
        
        string IMigrationMetadata.Id
        {
            get { return "201810301925511_added lat and long attribute to employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
