// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class splitupstreetaddressforusersdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(splitupstreetaddressforusersdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201810261329044_split up street address for users data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
